# @package _group_

name: ace_cdaweb

load:
  path: data/ace_cdaweb_combined.pkl
  features:
    - bx
    - by
    - bz
    - vx
    - density
    - temperature
    - x

# QUESTION: Where is this used?
columns:
  times: "times"
  speed: "vx"
  density: "density"
  temperature: "temperature"
  x_coord: "x"
  # status: ["status_swepam", "status_mag"]

new_features: []

pipeline:
  # Arguments for HydraPipeline
  order:
    - values_filter
    - filter
    # - propagate
    # - delete_cols
    - resample
    - add_features
    - interpolate
    - scaler_func
  interpolate:
    method: linear
    axis: 0
    limit_direction: both
    limit: 15
  resample:
    freq: "5T"
    func: "mean"
  scaler:
    scaler: null
    kwargs: null
  func:
    func: null
    inverse_func: null
    kwargs: null
  values_filter:
    bad_values: [-1e31]
    # bad_values: [-9999, 999, 999.9, -999.9]
    value_ranges:
      # Obtained from CDF metadata
      x: [-2000000, 2000000]
      density: [0, 200]
      vx: [-1800, 0]
      temperature: [1000, 1100000]
      bx: [-65534, 65534]
      by: [-65534, 65534]
      bz: [-65534, 65534]
  filter:
    type: "limited_change"
    speed_col: ${features.columns.speed}
    density_col: ${features.columns.density}
    temp_col: ${features.columns.temperature}
    copy: True
    limited_change:
      factor: 1.3
      change_down: 30
      change_ups: [50, 10]
  propagate:
    x_coord_col: ${features.columns.x_coord}
    speed_col: ${features.columns.speed}
    time_level: ${features.columns.times}
    delete_cols: false
    freq: "T"
    x_units: "km"
  delete_cols:
    - ${features.columns.x_coord}
    - ${features.columns.status}
  add_features:
    new_features: ${features.new_features}
