# @package _group_

name: ace_cdaweb

load:
  path: data/ace_cdaweb_siciliano.pkl
  # features:
  #   - "bx"
  #   - "by"
  #   - "bz"

columns:
  times: "times"
  # speed: "speed"
  # density: "density"
  # temperature: "temperature"
  # x_coord: "x"
  # status: ["status_swepam", "status_mag"]

pipeline:
  # Arguments for HydraPipeline
  order:
    - values_filter
    - filter
    # - propagate
    # - delete_cols
    - resample
    - interpolate
    - scaler_func
  interpolate:
    method: linear
    axis: 0
    limit_direction: both
    limit: 15
  resample:
    freq: "5T"
    func: "mean"
  scaler:
    scaler: null
    kwargs: null
  func:
    func: null
    inverse_func: null
    kwargs: null
  values_filter:
    bad_values: [-9999, 999, 999.9, -999.9]
    value_ranges:
      x: [0, 300]
      density: [0, 200]
      speed: [200, 2000]
      temperature: [1e4, 1e7]
      bx: [-200, 200]
      by: [-200, 200]
      bz: [-200, 200]
  filter:
    type: "limited_change"
    speed_col: ${features.columns.speed}
    density_col: ${features.columns.density}
    temp_col: ${features.columns.temperature}
    copy: True
    limited_change:
      factor: 1.3
      change_down: 30
      change_ups: [50, 10]
  propagate:
    x_coord_col: ${features.columns.x_coord}
    speed_col: ${features.columns.speed}
    time_level: ${features.columns.times}
    delete_cols: false
    freq: "T"
  delete_cols:
    - ${features.columns.x_coord}
    - ${features.columns.status}
