# INCOMPLETE
stages:
  concat_configs:
    desc: "Concatenate configs as as stage so that it doesn't rerun if nothing has changed." 
    cmd: python src/concat_configs.py
    deps:
      - configs/
      - src/concat_configs.py
    outs:
      # Get error when I just specify params/ here
      - params/process_data.yaml:
          cache: false
      - params/compute_lagged_features.yaml:
          cache: false
      - params/train.yaml:
          cache: false
  process_data:
    desc: "Process/split data before computing lagged features and fitting models."
    vars:
      - params/process_data.yaml
    cmd: python src/process_data.py
    deps:
      - src/preprocessing
      - src/process_data.py
      # - params/process_data.yaml
      - ${target.load.path}
      - ${features.load.path}
      - ${split.storm_times}
    params:
      - params/process_data.yaml:
        - start
        - end
        - seed
        - target
        - features
        - split
    outs:
      - ${hydra.run.dir}/
  compute_lagged_features:
    vars:
      - params/compute_lagged_features.yaml
    cmd: python src/compute_lagged_features.py
    deps:
      - src/compute_lagged_features.py
      # - params/compute_lagged_features.yaml
      - ${inputs_dir}/
    params:
      - params/compute_lagged_features.yaml:
          - lag
          - exog_lag
          - lead
          - inputs
    outs:
      - ${hydra.run.dir}
