# @package _global_

defaults:
  - hydra: default
  - target: supermag
  - features: solar_wind

symlink: false

time:
  start: 2010-01-01
  end: 2019-12-31

split:
  test_size: .2

output:
  features_pipeline: "features_pipeline.pkl"
  target_pipeline: "target_pipeline.pkl"
  train_features: "train_features.pkl"
  train_target: "train_target.pkl"
  test_features: "test_features.pkl"
  test_target: "test_target.pkl"
