# @package _global_

defaults:
  - target: supermag
  - features: solar_wind

hydra:
  run:
    dir: outputs/${hydra.job.name}/features=${solar_wind.name},target=${target.name}/${hydra.job.override_dirname}/
  # job:
  #   config:
  #     override_dirname:
  #       kv_sep: '-'
  #       item_sep: "_"

# Symlink data from data/processed
# Probably will delete this option
symlink: false

start: 2010-01-01
end: 2019-12-31

split:
  test_size: .2

output:
  features_pipeline: "features_pipeline.pkl"
  target_pipeline: "target_pipeline.pkl"
  train_features: "train_features.pkl"
  train_target: "train_target.pkl"
  test_features: "test_features.pkl"
  test_target: "test_target.pkl"
