# @package _global_

defaults:
  - hydra/sweeper: nevergrad
  - hydra/launcher: submitit_slurm
  - model: xgboost
  - cv: timeseries

hydra:
  sweep:
    dir: multirun/${model}/${now:%Y-%m-%d_%H-%M}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: "_"
        exclude_keys:
         - overrides
  
  # job_logging:
  #   level: INFO
  #   handlers:
  #   - file

# TODO: Change these to numbers  
lag: "H"
exog_lag: "H"
lead: "H"

features: solar_wind
target: symh
split: ${cv.method}

# TODO: Figure out how to specify overrrides nicer
overrides: ''


# DON'T OVERRIDE/CHANGE
load:
  # Keyword arguments for load_processed_data, load_processors in utils
  inputs_dir: outputs/process_data/features-${features}/target-${target}/split-${split}/${overrides}
  paths:
    features_pipeline: "features_pipeline.pkl"
    target_pipeline: "target_pipeline.pkl"
    train_features: "train_features.pkl"
    train_target: "train_target.pkl"
    test_features: "test_features.pkl"
    test_target: "test_target.pkl"
    group_labels: "group_labels.pkl"

# Inverse transform before computing metrics
inverse_transform: true

metric: "rmse"
