# @package _global_

model: ebm

param:
  max_bins: 256
  max_interaction_bins: 32
  binning: "quantile"
  mains: "all"
  interactions: 100
  outer_bags: 8
  inner_bags: 5
  learning_rate: 0.01
  validation_size: 0.15
  early_stopping_rounds: 50
  early_stopping_tolerance: 0.0001
  max_rounds: 5000
  min_samples_leaf: 2
  max_leaves: 3
  n_jobs: -2
  random_state: 8686
  
mlflow: true


outputs:
  model: "model.joblib"
