# @package _global_

model: xgboost

# TODO: Find way to separate this into new file
hydra:
  # launcher:
  #   mem_gb: 15
  #   cpus_per_task: 1
  #   additional_parameters:
  #     account: stats_dept1
  sweeper:
    optim:
      optimizer: NGOpt
      budget: 3
      num_workers: 1
    parametrization:
      param.learning_rate:
        # init: 0.2
        lower: 0.001
        upper: 0.6
      param.max_depth:
        integer: true
        # init: 6
        lower: 1
        upper: 9
      param.min_child_weight:
        integer: true
        # init: 2
        lower: 1
        upper: 4
      param.colsample_bytree:
        # init: 0.8
        lower: 0.5
        upper: 1.0

param:
  learning_rate: 0.2
  max_depth: 6
  min_child_weight: 2
  colsample_bytree: 0.8

mlflow: true
  
kwargs:
  num_boost_round: 30
  early_stopping_rounds: 10

outputs:
  model: "model.xgb"
  predictions: "ypred.pkl"
  cv_results: "cv_results.csv"
