# @package _global_

hydra:
  sweeper:
    parametrization:
      lagged_features.lag:
        integer: true
        step: 20
        lower: 40
        upper: 240
      lagged_features.exog_lag:
        integer: true
        step: 20
        lower: 60
        upper: 240
