# @package _global_

features: ace
target: symh
split: storms
data: {} # For specifying overrides in process_data

lag: 60
exog_lag: 60
lead: 60
history_freq: null
lag_processor:
  unit: "minutes"
  return_pandas: false

outputs:
  X_train: "X_train.npy"
  y_train: "y_train.pkl"
  X_test: "X_test.npy"
  y_test: "y_test.pkl"
  lag_processor: "lag_processor.pkl"
  features_name: "features_names.pkl"

hydra:
  verbose: false
  run:
    dir: outputs/lagged_features/${features}_${target}_${split}/${lag}_${exog_lag}_${lead}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        # kv_sep: "-"
        # item_sep: "_"
        exclude_keys:
          - target
          - features
          - split
          - target.loading.data_dir
          - features.loading.path
          - overrides
          - lag
          - exog_lag
          - lead
          - inputs_dir
          - inputs
          - outputs
