# @package _global_

features:
  name: ace
  # Any other overrides can go here
target:
  name: symh
split:
  method: storms
data: {}

# Times in minutes or frequency string
lag: 60
exog_lag: 60
lead: 60

history_freq: null
lag_processor:
  unit: "minutes"
  return_pandas: true

outputs:
  X_train: "X_train.pkl"
  y_train: "y_train.pkl"
  X_test: "X_test.pkl"
  y_test: "y_test.pkl"
  lag_processor: "lag_processor.pkl"
  features_names: "features_names.pkl"

hydra:
  verbose: false
  run:
    # dir: outputs/lagged_features/${data.features}_${data.target}_${data.split}/${lag}_${exog_lag}_${lead}/${hydra.job.override_dirname}
    dir: outputs/lagged_features/${features.name}_${target.name}_${split.method}/${lag}_${exog_lag}_${lead}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        # kv_sep: "-"
        # item_sep: "_"
        exclude_keys:
          - target.name
          - features.name
          - split.method
          - lag
          - exog_lag
          - lead
          - inputs_dir
          - inputs
          - outputs
