# @package _global_

# defaults:
#   - target: symh
#   - features: ace
#   - split: storms

# overrides: ''
    
lag: "H"
exog_lag: "H"
lead: "H"

hydra:
  verbose: false
  run:
    dir: outputs/lagged_features
  job:
    config:
      override_dirname:
        kv_sep: "-"
        item_sep: "_"
        exclude_keys:
          - target
          - features
          - split
          - target.loading.data_dir
          - features.loading.path
    
inputs_dir: outputs/processed_data
          
inputs:
  absolute: true
  paths:
    features_pipeline: "features_pipeline.pkl"
    target_pipeline: "target_pipeline.pkl"
    train_features: "train_features.pkl"
    train_target: "train_target.pkl"
    test_features: "test_features.pkl"
    test_target: "test_target.pkl"
    # group_labels: "group_labels.pkl"


outputs:
  X_train: "X_train.npy"
  y_train: "y_train.pkl"
  X_test: "X_test.npy"
  y_test: "y_test.pkl"
  lag_processor: "lag_processor.joblib"
