# @package _global_

defaults:
  - hydra/sweeper: nevergrad
  # - hydra/launcher: submitit_slurm
  # - sweeper: default
  - model: xgboost
  - cv: storms

data: {}
features:
  name: ace
target:
  name: symh
split:
  method: ${cv.method}
lagged_features: {}

seed: 8686
metrics: "rmse"

# mlflow
experiment_name: test
run_name: null
tags:
  test: true

# Inverse transform before computing metrics
inverse_transform: true
target_pipeline: target_pipeline.pkl

outputs:
  predictions: "ypred.pkl"

plot:
  persistence: true
  
hydra:
  verbose: false
  run:
    dir: outputs/train/${model}/${now:%Y-%m-%d_%H-%M}
  sweep:
    dir: multirun/${model}/${now:%Y-%m-%d_%H-%M}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        # kv_sep: '-'
        # item_sep: "_"
        exclude_keys:
         - overrides
