# @package _global_

defaults:
  - hydra/sweeper: nevergrad
  # - hydra/launcher: submitit_slurm
  - model: xgboost
  - cv: storms

hydra:
  verbose: false
  sweep:
    dir: multirun/${model}/${now:%Y-%m-%d_%H-%M}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: "_"
        exclude_keys:
         - overrides

features: ace
target: symh
split: ${cv.method}
# TODO: Figure out how to specify overrrides nicer
data_overrides: ''
features_overrides: ''
seed: 8686
# mlflow
experiment_name: geomag_forecasting

lag: 60
exog_lag: 60
lead: 60

processed_data_dir: outputs/processed_data/${features}_${target}_${split}/${data_overrides}

load:
  # Keyword arguments for load_processed_data, load_processors in utils
  inputs_dir: outputs/lagged_features/${features}_${target}_${split}/${data_overrides}/${lag}_${exog_lag}_${lead}/${features_overrides}
  paths:
    X_train: X_train.npy
    y_train: y_train.pkl
    X_test: X_test.npy
    y_test: y_test.pkl
    feature_names: features_names.pkl

# Inverse transform before computing metrics
inverse_transform: true
target_pipeline: target_pipeline.pkl
metrics: "rmse"

outputs:
  predictions: "ypred.pkl"
