# @package _global_

defaults:
  - hydra/sweeper: nevergrad
  # - hydra/launcher: submitit_slurm
  - model: xgboost
  - cv: storms

hydra:
  verbose: true
  sweep:
    dir: multirun/${model}/${now:%Y-%m-%d_%H-%M}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: "_"
        exclude_keys:
         - overrides
  
  # job_logging:
  #   level: INFO
  #   handlers:
  #   - file

# TODO: Change these to numbers  
lag: "H"
exog_lag: "H"
lead: "H"

features: omni
target: symh
split: ${cv.method}

# TODO: Figure out how to specify overrrides nicer
overrides: ''

experiment_name: geomag_forecasting
seed: 8686

processed_data_dir: outputs/processed_data

# DON'T OVERRIDE/CHANGE
load:
  # Keyword arguments for load_processed_data, load_processors in utils
  inputs_dir: outputs/lagged_features
  paths:
    target_pipeline: ../processed_data/target_pipeline.pkl
    X_train: X_train.npy
    y_train: y_train.pkl
    X_test: X_test.npy
    y_test: y_test.pkl
    feature_names: feature_names.pkl


# Inverse transform before computing metrics
inverse_transform: true

metric: "rmse"
