# @package _global_

defaults:
  - hydra/sweeper: nevergrad
  - model: xgboost
  - cv: storms
  - sweeper: default
  - lagged_features: default
  # - sweeper: tune_lags

features:
  name: ace
  # load:
  #   features:
  #     - bx
  #     - by
  #     - bz
target:
  name: symh
split:
  method: storms
data: {}
# lagged_features:
#   lag: 60
#   exog_lag: 60
#   lead: 60

seed: 8686
metrics: "rmse"

# mlflow
mlflow: true
experiment_name: test_tune
experiment_id: "3"
tags:
  tune: true

hydra:
  verbose: false
  sweep:
    dir: multirun/${model}/${now:%Y-%m-%d_%H-%M}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - experiment_name
          # - features.load.features
          - lagged_features
          - data
          - features
          - tags
          - experiment_id
          - split
