# @package _global_

defaults:
  - hydra/sweeper: nevergrad
  - model: xgboost
  - cv: storms
  - sweeper: default

hydra:
  verbose: false
  sweep:
    dir: multirun/${model}/${now:%Y-%m-%d_%H-%M}
    subdir: ${hydra.job.override_dirname}

features: ace
target: symh
split: ${cv.method}
seed: 8686
metrics: "rmse"

# mlflow
experiment_name: geomag_forecasting
