# @package _group_

run:
  dir: outputs/${now:%Y-%m-%d}/${hydra.job.name}/${hydra.job.override_dirname}/
# hydra_logging: disabled
job:
  config:
    override_dirname:
      kv_sep: '-'
      item_sep: "_"
