# @package _group_

name: supermag

load:
  data_dir: data/supermag
  station: "OTT"

  # Compute horizontal component
  horizontal: true

pipeline:
  order:
    - resample
    - interpolate
    - scaler_func
  interpolate: false
  resample:
    freq: '20T'
    func: "mean"
  # Name of sklearn transformer. Must be within scope in src/process_data.py
  scaler: 
    scaler: null
    kwargs: null
  func:
    func: null
    # func: "np.log"
    inverse_func: null
    # inverse_func: "np.exp"
    kwargs: null

  # Other keyword arguments for scaler or func can also be passed
