# @package _global_

model: xgboost

hydra:
  sweeper:
    optim:
      optimizer: OnePlusOne
      budget: 100
      num_workers: 4
    parametrization:
      param.learning_rate:
        init: 0.2
        lower: 0.001
        upper: 0.6

kwargs:
  num_boost_round: 100
  early_stopping_rounds: 30
  metrics: "rmse"

param:
  learning_rate: 0.2

outputs:
  model: "model.xgb"
  cv_results: "cv_results.csv"
